src/ART/MontereyBayAquiarum.Swat.Web/Controllers/AnalysisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using ART;
using MontereyBayAquarium.Swat.Web.Models.Analysis;
using MontereyBayAquarium.Swat.Web.ActionResults;
using MontereyBayAquarium.Swat.Web.Models;
using System.Net;
using System.Net.Mail;
using ART.Reporting;

namespace MontereyBayAquarium.Swat.Web.Controllers
{
    [Authorize]
    public class AnalysisController : ControllerBase
    {

        #region Define Scope
        [HttpGet]
        public ViewResult DefineScope(int id)
        {
            ReportEntity report = new ReportEntity(id);
            DefineScopeViewModel model = new DefineScopeViewModel()
            {
                Recommendations = Service.RecsByReport(report),
                RecommendationTypes = Service.RecommendationType()
            };

            return View("DefineScope", model);
        }

        [HttpPost]
        public JsonNetResult SaveScope(int id, int recommendationId, int speciesId, int? locationId, int? bodyOfWaterId, int methodId, int typeId)
        {
            int result = 0;
            bool success = true;
            if (locationId == null)
            {
                locationId = 0;
            }
            if (bodyOfWaterId == null)
            {
                bodyOfWaterId = 0;
            }

            try
            {
                if (recommendationId == 0)
                    result = Service.RecommendationCreate(id, speciesId, (int)locationId, (int)bodyOfWaterId, methodId, typeId);
                else
                    result = Service.RecommendationUpdate(id, recommendationId, speciesId, (int)locationId, (int)bodyOfWaterId, methodId, typeId);
            }
            catch
            {
                result = 0;
            }
            if (result == 0)
            {
                success = false;
            }
            else
            {
                success = true;
            }
            return new JsonNetResult(new { Success = success, recId = result });
        }

        [HttpPost]
        public JsonNetResult UpdateRecommendation(int id, int recommendationId, int typeId)
        {
            //5 for no, 4 for yes
            int result = Service.RecommendationUpdateType(id, recommendationId, typeId);
            bool success;
            if (result == 0)
                success = false;
            else
                success = true;
            return new JsonNetResult(new { Success = success, typeId = typeId });
        }

        [HttpPost]
        public JsonNetResult DeleteScope(int id, int recommendationId)
        {
            bool result = Service.RecommendationDelete(id, recommendationId);
            return new JsonNetResult(new { Success = result });
        }

        #endregion

        #region StockHealth
        [HttpGet]
        public ViewResult StockHealth(int id)
        {
            IList<Criteria1Entity> model = Service.StockHealthOverview(id).OrderBy(x => x.CommonName).ToList();
            //Todo: need to pass in title/label of Factor, for now it's hardcoded in
            return View("StockHealth", model);
        }
        #endregion

        #region Criteria1
        [HttpGet]
        public ViewResult Criteria1(int id)
        {
            Criteria1ViewModel model = new Criteria1ViewModel()
            {
                Criteria = Service.Criteria1Overview(id).OrderBy(x => x.CommonName).ToList(),
                Synthesis = Service.SynthesisGet(id, 1)
            };
            return View("Criteria1", model);
        }
        #endregion

        #region Criteria2
        [HttpGet]
        public ViewResult Criteria2(int id)
        {
            IList<Criteria2Display> criteria = Helpers.BuildCriteria2List(Service.Criteria2Overview(id));

            Criteria2ViewModel model = new Criteria2ViewModel()
            {
                Criteria = criteria,
                Criteria21 = Service.Criteria21Overview(id).OrderBy(x => x.CommonName).ToList(), //TODO: Replace with the correct service method call when that's done
                Criteria24 = Service.Criteria24Overview(id).OrderBy(x => x.Location).ToList(),
                Synthesis = Service.SynthesisGet(id, 2)
            };
            return View("Criteria2", model);
        }
        #endregion

        #region Criteria3
        [HttpGet]
        public ViewResult Criteria3(int id)
        {
            Criteria3Display criteria = new Criteria3Display()
            {
                SummaryCriteria = Service.Criteria3Overview(id),
                Criteria31 = Service.Criteria31Overview(id),
                Criteria32 = Service.Criteria32Overview(id)
            };
            Criteria3ViewModel model = new Criteria3ViewModel()
            {
                Synthesis1 = Service.SynthesisGet(id, 31),
                Synthesis2 = Service.SynthesisGet(id, 32),
                Synthesis3 = Service.SynthesisGet(id, 33),
                Criteria = criteria
            };
            return View("Criteria3", model);
        }
        #endregion

        #region Criteria4
        [HttpGet]
        public ViewResult Criteria4(int id)
        {
            Criteria4ViewModel model = new Criteria4ViewModel()
            {
                Criteria = Service.Criteria4Overview(id),
                Synthesis = Service.SynthesisGet(id, 4)
            };
            return View("Criteria4", model);
        }
        #endregion

        #region ExecutiveSummary
        [HttpGet]
        public ViewResult ExecutiveSummary(int id)
        {
            ViewBag.ExecutiveSummary = Service.TextBlockGet(id, ARTService.TextBlock.ExecSummary);
            return View("ExecutiveSummary");
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult ExecutiveSummary(int id, string executiveSummary, string nextAction)
        {
            //TODO: Client side form validation in javascript
            Service.TextBlockSet(id, ARTService.TextBlock.ExecSummary, executiveSummary);
            ViewBag.ExecutiveSummary = executiveSummary;
            return RedirectToAction(nextAction);
        }
        #endregion

        #region Introduction
        [HttpGet]
        public ViewResult Introduction(int id)
        {
            ViewBag.IntroductionScope = Service.TextBlockGet(id, ARTService.TextBlock.Scope);
            ViewBag.IntroductionSpeciesOverview = Service.TextBlockGet(id, ARTService.TextBlock.SpeciesOverview);
            ViewBag.ProductionStatistics = Service.TextBlockGet(id, ARTService.TextBlock.ProductionStatistics);
            ViewBag.ImportanceToMarket = Service.TextBlockGet(id, ARTService.TextBlock.ImportanceToMarket);
            ViewBag.CommonMarketNames = Service.TextBlockGet(id, ARTService.TextBlock.CommonMarketNames);
            ViewBag.ProductForms = Service.TextBlockGet(id, ARTService.TextBlock.ProductForms);
            return View("Introduction");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Introduction(int id, string introductionScope, string introductionSpeciesOverView, string productionStatistics, string importanceToMarket, string commonMarketNames, string productForms, string nextAction)
        {
            Service.TextBlockSet(id, ARTService.TextBlock.Scope, introductionScope);
            Service.TextBlockSet(id, ARTService.TextBlock.SpeciesOverview, introductionSpeciesOverView);
            Service.TextBlockSet(id, ARTService.TextBlock.ProductionStatistics, productionStatistics);
            Service.TextBlockSet(id, ARTService.TextBlock.ImportanceToMarket, importanceToMarket);
            Service.TextBlockSet(id, ARTService.TextBlock.CommonMarketNames, commonMarketNames);
            Service.TextBlockSet(id, ARTService.TextBlock.ProductForms, productForms);
            return RedirectToAction(nextAction);
        }
        #endregion

        #region Acknowledgements

        [HttpGet]
        public ViewResult Acknowledgements(int id)
        {
            ViewBag.Acknowledgements = Service.TextBlockGet(id, ARTService.TextBlock.Acknowledgements);
            return View("Acknowledgements");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Acknowledgements(int id, string acknowledgements, string nextAction)
        {
            Service.TextBlockSet(id, ARTService.TextBlock.Acknowledgements, acknowledgements);
            return RedirectToAction(nextAction);
        }
        #endregion

        #region SupplementalInfo

        [HttpGet]
        public ViewResult SupplementalInfo(int id)
        {
            @ViewBag.SupplementalInfo = Service.TextBlockGet(id, ARTService.TextBlock.SupplementalInfo);
            return View("SupplementalInfo");
        }


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SupplementalInfo(int id, string supplementalInfo, string nextAction)
        {
            Service.TextBlockSet(id, ARTService.TextBlock.SupplementalInfo, supplementalInfo);
            return RedirectToAction(nextAction);
        }
        #endregion

        #region Appendix
        [HttpGet]
        public ViewResult Appendix(int id)
        {

            AppendixViewModel model = new AppendixViewModel();
            model.Appendices = Service.AppendixesGet(id);
            model.ReviewSchedule = Service.TextBlockGet(id, ARTService.TextBlock.ReviewSchedule);
            return View("Appendix", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Appendix(int id, string[] appendixTitles, string[] appendixDetails, int[] appendixId, string reviewSchedule, string nextAction)
        {  // should always return atleast one empty instance of an array
            //var newList = appendixTitles.ToList();
            for (var i = 0; i < appendixTitles.Length; i++)
            {
                if (appendixDetails[i].Length == 0 && appendixTitles[i].Length == 0)

src/ART/MontereyBayAquiarum.Swat.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ART;
using MontereyBayAquarium.Swat.Web.Models;
using System.Net;
using System.Net.Mail;

namespace MontereyBayAquarium.Swat.Web.Controllers
{
    [Authorize]
    public class DashboardController : ControllerBase
    {

        public ViewResult Index(AuthenticatedUser user)
        {
            ReportsViewModel model = new ReportsViewModel()
            {
                Reports = Service.ReportList(user.UserEntity, ""),
                User = user.UserEntity
            };
            return View("Index", model);
        }

        public ActionResult CompleteReview(int id, AuthenticatedUser user)
        {
            
            //Service.UpdateReportStatus(id, 5); //5 = Internal Review 2
            ReportEntity report = Service.LoadReport(id);
            HttpContext.Session["Report"] = report;
            string subject = "Report review complete";
            string body = user.DisplayName + "has completed review of the following report:\n\n" + report.Title + "\n\n This report is now ready for Internal Review 2.";
            Helpers.SendMail(subject, body);
            TempData["Completed"] = true;
            Service.ReviewerReviewed(id, user.Id); 
            return RedirectToAction("Index");
        }

        public ActionResult UncompleteReview(int id, AuthenticatedUser user)
        {
            Service.ReviewerUnReviewed(id, user.Id);
            return RedirectToAction("Index");
        }

    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Views/Dashboard/Index.cshtml
@model MontereyBayAquarium.Swat.Web.Models.ReportsViewModel
@using ART;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LoggedInLayout.cshtml";
}
<div class="public-wrapper dashboard-reports-container">
    <!--Reviewer table-->
    @if (Model.Reports.Where(r => r.HasAccess(ReportEntity.Permission.CompleteReview)).Count() > 0 && Model.User.IsSFWStaff == false)
    {
        @Html.Action("GuidingPrinciple", "Analysis", new { title = "Before You Start", key = "ReviewerStart" })
        
        <h3>The following reports are ready for your review:</h3>
        <table class="review-table" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <th class="left-cap seventy">Report
                </th>
                <th class="fifteen">Last Commented
                </th>
                <th class="right-cap fifteen"></th>
            </tr>

            @foreach (ReportEntity report in Model.Reports)
            {
                if (report.HasAccess(ReportEntity.Permission.CompleteReview))
                {
                <tr>
                    <td class="left-cap">
                        <a href="@Url.Action("ExecutiveSummary", "Review", new { id = report.Id })">@report.Title</a>
                    </td>
                    <td class="date">
                        <span>@report.LastUpdated</span>
                    </td>
                    <td class="right-cap">
                        <a class="button-review review-complete" href="@Url.Action("CompleteReview", "Dashboard", new { id = report.Id })"><span class="l">Submit Review to Seafood Watch</span><span class="r"></span></a>
                    </td>
                </tr>
                }
            }
        </table>
    }
    <!--Analyst table-->

    @if (Model.Reports.Where(r => r.HasAccess(ReportEntity.Permission.Answer)).Count() > 0 && Model.User.IsSFWStaff == false)
    {
        @Html.Action("GuidingPrinciple", "Analysis", new { title = "What's New", key = "WhatsNew" })
        @Html.Action("GuidingPrinciple", "Analysis", new { title = "Before You Start", key = "BeforeYouStart" })
        <h3>You are analyzing the following reports:</h3>
        <table class="analysis-table" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <th class="left-cap forty-five">Report
                </th>
                <th class="fifteen">Last Updated
                </th>
                <th class="fifteen">Status
                </th>
                <th class="right-cap ten"></th>
            </tr>
            @foreach (ReportEntity report in Model.Reports)
            {
                if (report.HasAccess(ReportEntity.Permission.Answer))
                {
                <tr>
                    <td class="left-cap">
                        <a href="@Url.Action("DefineScope", "Analysis", new { id = report.Id })">@report.Title</a>
                    </td>
                    <td class="date">
                        <span>@report.LastUpdated</span>
                    </td>
                    <td class="status @report.ReportStatus.ToLowerInvariant().Replace(" ", "-")">
                        <span>@report.ReportStatus</span>
                    </td>
                    <td class="right-cap">
                        @if (report.HasAccess(ReportEntity.Permission.ExportReport))
                        {
                            <a class="button-review" href="@Url.Action("Export", "Analysis", new { id = report.Id })"><span class="l">Export</span><span class="r"></span></a>
                            <a class="button-review" href="@Url.Action("SubmitReport", "Analysis", new { id = report.Id })"><span class="l">Submit For Review</span><span class="r"></span></a>
                        }
                    </td>
                </tr>
                }
            }
        </table>
    }
    <!--SWAT Table-->

    @if (Model.Reports.Where(r => r.HasAccess(ReportEntity.Permission.UpdateStatus)).Count() > 0)
    {
        @Html.Action("GuidingPrinciple", "Analysis", new { title = "Before You Start", key = "BeforeYouStart" })
        <h3>You are managing the following reports:</h3>
        <table class="analysis-table" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <th class="left-cap forty-five">Report
                </th>
                <th class="fifteen">Last Updated
                </th>
                <th class="fifteen">Status
                </th>
                <th class="right-cap ten"></th>
            </tr>
            @foreach (ReportEntity report in Model.Reports)
            {
                if (report.HasAccess(ReportEntity.Permission.UpdateStatus))
                {
                <tr>
                    <td class="left-cap">
                        <a href="@Url.Action("DefineScope", "Analysis", new { id = report.Id })">@report.Title</a>
                    </td>
                    <td class="date">
                        <span>@report.LastUpdated</span>
                    </td>
                    <td class="status @report.ReportStatus.ToLowerInvariant().Replace(" ", "-")">
                        <span>@report.ReportStatus</span>
                    </td>
                    <td class="right-cap">
                        @if (report.HasAccess(ReportEntity.Permission.ExportReport))
                        {
                            <a class="button-review" href="@Url.Action("Export", "Analysis", new { id = report.Id })"><span class="l">Export</span><span class="r"></span></a>
                            <a class="button-review" href="@Url.Action("SubmitReport", "Analysis", new { id = report.Id })"><span class="l">Submit For Review</span><span class="r"></span></a>
                        }
                    </td>
                </tr>
                }
            }
        </table>

    }

</div>
<script data-main="views/dashboard/index" src="@Url.Content("~/Scripts/libs/require.js")" type="text/javascript"></script>
@{if (ViewContext.TempData["Completed"] != null && (bool)ViewContext.TempData["Completed"])
  { 
    <div id="notification-modal" title="Thank you!">
        <p class="on">Thank you for providing comments on our draft assessment; we really appreciate your time and expertise in this matter. We will incorporate your feedback into the final draft, which will be posted on our website once it is complete.  If you have any questions, contact <a href="mailto:SFWResearch@mbayaq.org">SFWResearch@mbayaq.org</a>.</p>
    </div>

  }
}