src/ART/MontereyBayAquiarum.Swat.Web/Models/References/ReferencesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ART;

namespace MontereyBayAquarium.Swat.Web.Models.References
{
    public class ReferencesViewModel
    {
        public IList<ReferenceEntity> References { get; set; }
  
    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Controllers/AnalysisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using ART;
using MontereyBayAquarium.Swat.Web.Models.Analysis;
using MontereyBayAquarium.Swat.Web.ActionResults;
using MontereyBayAquarium.Swat.Web.Models;
using System.Net;
using System.Net.Mail;
using ART.Reporting;

namespace MontereyBayAquarium.Swat.Web.Controllers
{
    [Authorize]
    public class AnalysisController : ControllerBase
    {

        #region Define Scope
        [HttpGet]
        public ViewResult DefineScope(int id)
        {
            ReportEntity report = new ReportEntity(id);
            DefineScopeViewModel model = new DefineScopeViewModel()
            {
                Recommendations = Service.RecsByReport(report),
                RecommendationTypes = Service.RecommendationType()
            };

            return View("DefineScope", model);
        }

        [HttpPost]
        public JsonNetResult SaveScope(int id, int recommendationId, int speciesId, int? locationId, int? bodyOfWaterId, int methodId, int typeId)
        {
            int result = 0;
            bool success = true;
            if (locationId == null)
            {
                locationId = 0;
            }
            if (bodyOfWaterId == null)
            {
                bodyOfWaterId = 0;
            }

            try
            {
                if (recommendationId == 0)
                    result = Service.RecommendationCreate(id, speciesId, (int)locationId, (int)bodyOfWaterId, methodId, typeId);
                else
                    result = Service.RecommendationUpdate(id, recommendationId, speciesId, (int)locationId, (int)bodyOfWaterId, methodId, typeId);
            }
            catch
            {
                result = 0;
            }
            if (result == 0)
            {
                success = false;
            }
            else
            {
                success = true;
            }
            return new JsonNetResult(new { Success = success, recId = result });
        }

        [HttpPost]
        public JsonNetResult UpdateRecommendation(int id, int recommendationId, int typeId)
        {
            //5 for no, 4 for yes
            int result = Service.RecommendationUpdateType(id, recommendationId, typeId);
            bool success;
            if (result == 0)
                success = false;
            else
                success = true;
            return new JsonNetResult(new { Success = success, typeId = typeId });
        }

        [HttpPost]
        public JsonNetResult DeleteScope(int id, int recommendationId)
        {
            bool result = Service.RecommendationDelete(id, recommendationId);
            return new JsonNetResult(new { Success = result });
        }

        #endregion

        #region StockHealth
        [HttpGet]
        public ViewResult StockHealth(int id)
        {
            IList<Criteria1Entity> model = Service.StockHealthOverview(id).OrderBy(x => x.CommonName).ToList();
            //Todo: need to pass in title/label of Factor, for now it's hardcoded in
            return View("StockHealth", model);
        }
        #endregion

        #region Criteria1
        [HttpGet]
        public ViewResult Criteria1(int id)
        {
            Criteria1ViewModel model = new Criteria1ViewModel()
            {
                Criteria = Service.Criteria1Overview(id).OrderBy(x => x.CommonName).ToList(),
                Synthesis = Service.SynthesisGet(id, 1)
            };
            return View("Criteria1", model);
        }
        #endregion

        #region Criteria2
        [HttpGet]
        public ViewResult Criteria2(int id)
        {
            IList<Criteria2Display> criteria = Helpers.BuildCriteria2List(Service.Criteria2Overview(id));

            Criteria2ViewModel model = new Criteria2ViewModel()
            {
                Criteria = criteria,
                Criteria21 = Service.Criteria21Overview(id).OrderBy(x => x.CommonName).ToList(), //TODO: Replace with the correct service method call when that's done
                Criteria24 = Service.Criteria24Overview(id).OrderBy(x => x.Location).ToList(),
                Synthesis = Service.SynthesisGet(id, 2)
            };
            return View("Criteria2", model);
        }
        #endregion

        #region Criteria3
        [HttpGet]
        public ViewResult Criteria3(int id)
        {
            Criteria3Display criteria = new Criteria3Display()
            {
                SummaryCriteria = Service.Criteria3Overview(id),
                Criteria31 = Service.Criteria31Overview(id),
                Criteria32 = Service.Criteria32Overview(id)
            };
            Criteria3ViewModel model = new Criteria3ViewModel()
            {
                Synthesis1 = Service.SynthesisGet(id, 31),
                Synthesis2 = Service.SynthesisGet(id, 32),
                Synthesis3 = Service.SynthesisGet(id, 33),
                Criteria = criteria
            };
            return View("Criteria3", model);
        }
        #endregion

        #region Criteria4
        [HttpGet]
        public ViewResult Criteria4(int id)
        {
            Criteria4ViewModel model = new Criteria4ViewModel()
            {
                Criteria = Service.Criteria4Overview(id),
                Synthesis = Service.SynthesisGet(id, 4)
            };
            return View("Criteria4", model);
        }
        #endregion

        #region ExecutiveSummary
        [HttpGet]
        public ViewResult ExecutiveSummary(int id)
        {
            ViewBag.ExecutiveSummary = Service.TextBlockGet(id, ARTService.TextBlock.ExecSummary);
            return View("ExecutiveSummary");
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult ExecutiveSummary(int id, string executiveSummary, string nextAction)
        {
            //TODO: Client side form validation in javascript
            Service.TextBlockSet(id, ARTService.TextBlock.ExecSummary, executiveSummary);
            ViewBag.ExecutiveSummary = executiveSummary;
            return RedirectToAction(nextAction);
        }
        #endregion

        #region Introduction
        [HttpGet]
        public ViewResult Introduction(int id)
        {
            ViewBag.IntroductionScope = Service.TextBlockGet(id, ARTService.TextBlock.Scope);
            ViewBag.IntroductionSpeciesOverview = Service.TextBlockGet(id, ARTService.TextBlock.SpeciesOverview);
            ViewBag.ProductionStatistics = Service.TextBlockGet(id, ARTService.TextBlock.ProductionStatistics);
            ViewBag.ImportanceToMarket = Service.TextBlockGet(id, ARTService.TextBlock.ImportanceToMarket);
            ViewBag.CommonMarketNames = Service.TextBlockGet(id, ARTService.TextBlock.CommonMarketNames);
            ViewBag.ProductForms = Service.TextBlockGet(id, ARTService.TextBlock.ProductForms);
            return View("Introduction");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Introduction(int id, string introductionScope, string introductionSpeciesOverView, string productionStatistics, string importanceToMarket, string commonMarketNames, string productForms, string nextAction)
        {
            Service.TextBlockSet(id, ARTService.TextBlock.Scope, introductionScope);
            Service.TextBlockSet(id, ARTService.TextBlock.SpeciesOverview, introductionSpeciesOverView);
            Service.TextBlockSet(id, ARTService.TextBlock.ProductionStatistics, productionStatistics);
            Service.TextBlockSet(id, ARTService.TextBlock.ImportanceToMarket, importanceToMarket);
            Service.TextBlockSet(id, ARTService.TextBlock.CommonMarketNames, commonMarketNames);
            Service.TextBlockSet(id, ARTService.TextBlock.ProductForms, productForms);
            return RedirectToAction(nextAction);
        }
        #endregion

        #region Acknowledgements

        [HttpGet]
        public ViewResult Acknowledgements(int id)
        {
            ViewBag.Acknowledgements = Service.TextBlockGet(id, ARTService.TextBlock.Acknowledgements);
            return View("Acknowledgements");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Acknowledgements(int id, string acknowledgements, string nextAction)
        {
            Service.TextBlockSet(id, ARTService.TextBlock.Acknowledgements, acknowledgements);
            return RedirectToAction(nextAction);
        }
        #endregion

        #region SupplementalInfo

        [HttpGet]
        public ViewResult SupplementalInfo(int id)
        {
            @ViewBag.SupplementalInfo = Service.TextBlockGet(id, ARTService.TextBlock.SupplementalInfo);
            return View("SupplementalInfo");
        }


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SupplementalInfo(int id, string supplementalInfo, string nextAction)
        {
            Service.TextBlockSet(id, ARTService.TextBlock.SupplementalInfo, supplementalInfo);
            return RedirectToAction(nextAction);
        }
        #endregion

        #region Appendix
        [HttpGet]
        public ViewResult Appendix(int id)
        {

            AppendixViewModel model = new AppendixViewModel();
            model.Appendices = Service.AppendixesGet(id);
            model.ReviewSchedule = Service.TextBlockGet(id, ARTService.TextBlock.ReviewSchedule);
            return View("Appendix", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Appendix(int id, string[] appendixTitles, string[] appendixDetails, int[] appendixId, string reviewSchedule, string nextAction)
        {  // should always return atleast one empty instance of an array
            //var newList = appendixTitles.ToList();
            for (var i = 0; i < appendixTitles.Length; i++)
            {
                if (appendixDetails[i].Length == 0 && appendixTitles[i].Length == 0)

src/ART/MontereyBayAquiarum.Swat.Web/Controllers/ReferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ART;
using MontereyBayAquarium.Swat.Web.Models.References;
using MontereyBayAquarium.Swat.Web.ActionResults;
using System.Text.RegularExpressions;



namespace MontereyBayAquarium.Swat.Web.Controllers
{
    public class ReferenceController : ControllerBase
    {

        #region Index

        public ViewResult Index(int id, string keywords)
        {
            string Keywords = "";
            if (keywords != null) { Keywords = keywords; }
            ReferencesViewModel model = new ReferencesViewModel();
            model.References = Service.ReferenceList(id, Keywords);
            return View("Index", model);
        }
        #endregion

        #region Edit
        [HttpGet]
        public ViewResult Edit(int id, int referenceId)
        {
            ReferenceEntity model = Service.ReferenceGet(id, referenceId);
            return View("Edit", model);
        }
        
        
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, int referenceId, ReferenceEntity reference, HttpPostedFileBase documentation, string documentationType, string link)
        {
            //reference.Title = ""; //title is no longer needed TODO: Update Service Layer to take out title field
            bool isUrl = false;
            string path = "";
            RegexOptions options = RegexOptions.None;
            Regex regex = new Regex(@"[ ]{2,}", options);
            reference.ShortName = regex.Replace(reference.ShortName, @" ");
            if (reference.ReferenceId > 0)
            {
                ReferenceEntity oldReference = Service.ReferenceGet(reference.ReportId, reference.ReferenceId); // get the actual reference because there's no "path" or "isUrl" in the form
                isUrl = oldReference.isUrl;
                path = (oldReference.Path != null) ? oldReference.Path : "";
            }
            if (documentationType == "link") //documentationType = 0 unless the user purposefully want to upload something 
            {
                isUrl = true;
                path =  new UriBuilder(link).Uri.AbsoluteUri;
            }
           
			if (documentationType == "document") path = Helpers.SaveFile(documentation, Server, "references/"+id.ToString()+"/");

            bool shortNameIsValid = true;
            int updatedReferenceId = 0;

			if (reference.ReferenceId > 0)
                shortNameIsValid = Service.ReferenceUpdate(id, reference.ReferenceId, reference.ShortName, reference.Bibliography, reference.Authors, reference.Year, path, isUrl); //TODO GenEx
			else 
			    updatedReferenceId = Service.ReferenceAdd(id, reference.ShortName, reference.Bibliography, reference.Authors, reference.Year, path, isUrl); //TODO GenEx

            if (!shortNameIsValid || updatedReferenceId == -1)
            {
                TempData["error"] = "An existing reference already exists with the same shortname.";
                return RedirectToAction("Edit", new { id = id, referenceId = referenceId });
            }
			
			return RedirectToAction("Index");
        }
        #endregion

        [HttpPost]
        public JsonNetResult Delete(int id, int referenceId)
        {
            Service.ReferenceDelete(id, referenceId);
            return new JsonNetResult(new {success = true});
        }
        [HttpPost]
        public ActionResult Search(int id, string filter, string context)
        {
            ViewBag.Context = context;
            string Keywords = "";
            if (filter != null) { Keywords = filter; }
            ReferencesViewModel model = new ReferencesViewModel();
            model.References = Service.ReferenceList(id, Keywords);
            //return View("Index", model);
            return View("_References", model);
        }

        [HttpGet]
        public ViewResult Search(int id)
        {
            ViewBag.Context = "Modal";
            string Keywords = "";
            ReferencesViewModel model = new ReferencesViewModel();
            model.References = Service.ReferenceList(id, Keywords);
            return View("_References", model);
        }

    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Views/Reference/Edit.cshtml
@model ART.ReferenceEntity
@using System.IO;
@{
    ViewBag.Title = (Model.ReferenceId > 0) ? "Edit" : "Add";
    Layout = "~/Views/Shared/_AnalysisLayout.cshtml";
}
<div class="references edit-page">
<h2>@(Model.ReferenceId > 0 ? "Edit" : "Add") Reference</h2>
            @Html.Action("GuidingPrinciple", "Analysis", new { title = "Help", key = "References" })
        <p class="error-message">@(TempData["error"])</p>
@using (Html.BeginForm("Edit", "Reference", new { id = Convert.ToInt32(ViewContext.RouteData.Values["id"]), referenceId = Convert.ToInt32(ViewContext.RouteData.Values["referenceId"]) }, FormMethod.Post, new { @class = "details", id = "reference-form", enctype = "multipart/form-data" }))
{   <input type="hidden" value="@Model.ReferenceId" id="referenceid" name="referenceid" />
    <input type="hidden" value="@ViewContext.RouteData.Values["id"]" id="reportid" name="reportid" />
    <ul>
        <li>
            <label class="field-name-text">Author(s):</label>
            <input class="required" id="authors" name="authors" value="@Model.Authors" />
        </li>
        <li>
            <label class="field-name-text">Year:</label>
            <input class="required number" id="year" name="year" value="@Model.Year" maxlength="4"/>
        </li>
        <li>
            <label class="field-name-text">Short Name:</label>
            <input class="required" id="shortname" name="shortname" value="@Model.ShortName" />
        </li>
        <li>
            <label class="field-name-text">Bibliography:</label>
            <textarea class="required mceEditor" id="bibliography" name="bibliography">@Model.Bibliography</textarea>
        </li>
        <li class="edit-doc">
            <label class="field-name-text">Documentation:</label>
            <select class="required" id="documentationType" name="documentationType">
                <option value="0">Select One</option>
                <option value="document">Document</option>
                <option value="link">Link</option>
            </select>
            <input class="" value="@if(!Model.isUrl) { @Model.Path}" title="" type="file" id="documentation" name="documentation" />
            <input class="" value="@if(Model.isUrl) { @Model.Path}" title="" type="text" id="link" name="link" />
        </li>
<!-- Edit area starts here -->
        <li  class="view-doc">
            <label class="field-name-text">Documentation:</label>
            @if (Model.Path != null && Model.Path.Length > 0)
            {
                    if (Model.isUrl)
                    {
                        <a href="@Url.Content(Model.Path)">@Model.Path</a>
                    }
                    else
                    {
                        <span class="documentation-text">
                            <a href="/download?filename=@HttpUtility.UrlEncode(Model.Path)">@HttpUtility.UrlDecode(Model.Path)</a>
                        </span>
                    }
            }
        </li>
        <li class="view-doc update-link">
           <a>Update Link</a>
        </li>
        <li><a class="save-area submit button-on"><span class="l">Save Changes</span><span class="r"></span></a><span class="cancel-area"> or <a href="@Url.Action("Index", "Reference")">Cancel</a></span></li>
    </ul>
}
</div>

<div class="clear"></div>
<script data-main="views/reference/edit" src="@Url.Content("~/Scripts/libs/require.js")" type="text/javascript"></script>

src/ART/MontereyBayAquiarum.Swat.Web/Views/Reference/Index.cshtml
@model MontereyBayAquarium.Swat.Web.Models.References.ReferencesViewModel
@using ART;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AnalysisLayout.cshtml";
}

<div class="references">
<a class="button-review bulk-add"  href="/reports/@ViewContext.RouteData.Values["id"]/references/0/edit">
<span class="l">Add Reference</span>
<span class="r"></span>
<span class="plus"></span>
</a>
<h2>References</h2>
<div id="reference-container">
@Html.Partial("_References", Model)
</div>
</div>
@Html.Partial("_DeleteConfirmationModal")
<script data-main="views/reference/index" src="@Url.Content("~/Scripts/libs/require.js")" type="text/javascript"></script>