src/ART/MontereyBayAquiarum.Swat.Web/Models/Answer/EditAnswerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ART;

namespace MontereyBayAquarium.Swat.Web.Models.Answer
{
    public class EditAnswerViewModel
    {
        public FactorEntity Factor { get; set; }
        public IList<RowsourceEntity> FactorTypes { get; set; }
        public IList<RowsourceEntity> Scores { get; set; }
    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Models/References/ReferencesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ART;

namespace MontereyBayAquarium.Swat.Web.Models.References
{
    public class ReferencesViewModel
    {
        public IList<ReferenceEntity> References { get; set; }
  
    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Models/Shared/AnswerCellViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MontereyBayAquarium.Swat.Web.Models.Analysis;

namespace MontereyBayAquarium.Swat.Web.Models.Shared
{
    public class AnswerCellViewModel
    {
        public AnswerEntity Answer { get; set; }
        public string FactorTypeName { get; set; }
        public string Species { get; set; }
        public string Location { get; set; }
        public string BodyOfWater { get; set; }
        public string Method { get; set; }
        public bool IsEditable { get; set; }

        public AnswerCellViewModel()
        {
            IsEditable = true;
        }
    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Models/Shared/AnswerListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ART;

namespace MontereyBayAquarium.Swat.Web.Models.Shared
{
    public class AnswerListViewModel
    {
        public IList<FactorEntity> Answers { get; set; }
        public IList<RowsourceEntity> FactorTypes { get; set; }
        public int CurrentFactorTypeId { get; set; }
    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ART;
using MontereyBayAquarium.Swat.Web.Models.Answer;
using MontereyBayAquarium.Swat.Web.ActionResults;
using MontereyBayAquarium.Swat.Web.Models.Shared;

namespace MontereyBayAquarium.Swat.Web.Controllers
{
    public class AnswerController : ControllerBase
    {
        #region Answer List
        [HttpGet]
        public ViewResult Index(int id)
        {
            return View("Index");
        }
        #endregion

        #region Answer Edit
        [HttpGet]
        public ViewResult Edit(int id, int answerId)
        {
            return View("Edit");
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(int id, int answerId, int factorTypeId, int scoreId, string keyInfo, string rationale, string title = "")
        {
            FactorEntity temp = null;
            if (answerId > 0)
            {
                temp = Service.FactorUpdate(id, answerId, factorTypeId, scoreId, title, keyInfo, rationale);
            }
            else
            {
                temp = Service.FactorAdd(id, factorTypeId, scoreId, title, keyInfo, rationale);
                answerId = temp.Id;
            }
            string label = temp.Label;
            return RedirectToAction("Index", new { id = id });
        }

        #endregion

        [HttpPost]
        #region Answer Delete
        public JsonNetResult Delete(int id, int answerId)
        {
            FactorEntity factor = Service.FactorGet(answerId);
            Service.FactorDelete(id, answerId, factor.FactorTypeId);

            return new JsonNetResult(new { FactorId = answerId, Success = true });
        }
        #endregion

        #region Child Actions & Actions Returning Partial Views
        [HttpGet]
        public PartialViewResult AnswerDetail(int id, int answerId, string callingPage)
        {
            FactorEntity model = Service.FactorGet(answerId);
            ViewBag.CallingPage = callingPage;
            return PartialView("_AnswerDetail", model);
        }

        /// <summary>
        /// Get all answers for a specific factory type, as opposed to the index method, which gets all answers in general
        /// </summary>
        /// <param name="id"></param>
        /// <param name="factorTypeId"></param>
        /// <returns></returns>
        [HttpGet]
        public PartialViewResult AnswerList(int id, int factorTypeId)
        {
            IList<RowsourceEntity> FactorTypes = Service.FactorType();
            AnswerListViewModel model = new AnswerListViewModel()
            {
                Answers = Service.FactorGet(id, factorTypeId,""), //TODO IMplement filter
                FactorTypes = Service.FactorType(),
                CurrentFactorTypeId = factorTypeId
            };
            //FactorTypeEntity factorType = null;
            //if (factorTypeId > 0) factorType = Service.FactorTypeGet(factorTypeId);
            //model.FactorType = factorType;

            return PartialView("_AnswerList", model);
        }

        [HttpPost]
        public PartialViewResult AnswerList(int id, int factorTypeId, string filter)
        {
            IList<RowsourceEntity> FactorTypes = Service.FactorType();
            AnswerListViewModel model = new AnswerListViewModel()
            {
                Answers = Service.FactorGet(id, factorTypeId, filter),
                FactorTypes = Service.FactorType(),
                CurrentFactorTypeId = factorTypeId
            };
            return PartialView("_AnswerList", model);
        }

        [HttpGet]
        public PartialViewResult EditAnswer(int id, int answerId, int factorTypeId, string context = null) //We need the factortype in the case of adding a new factor--need to know which factor types to display in the drop down list on the form
        {
            if (context == "criteria2")
            {
                TempData["context"] = context;
            }
            EditAnswerViewModel model = new EditAnswerViewModel()
            {
                Factor = (answerId > 0) ? Service.FactorGet(answerId) : new FactorEntity(),
            };
            if (answerId > 0)
            {
                factorTypeId = model.Factor.FactorTypeId;
            }
            IList<RowsourceEntity> factorTypes = Service.FactorType();
            IList<RowsourceEntity> scores = null;
            if (factorTypeId > 0)
            {
                var factorType = factorTypes.Where(x => x.Key == factorTypeId).FirstOrDefault();
                factorTypes = new List<RowsourceEntity>();
                factorTypes.Add(factorType);
                scores = Service.FactorScore(model.Factor.FactorTypeId);
            }
            model.FactorTypes = factorTypes.OrderBy(x => x.Value).ToList();
            model.Scores = scores;
            model.Factor.FactorTypeId = factorTypeId;
            return PartialView("_EditAnswer", model);
        }

        [HttpPost, ValidateInput(false)]
        public JsonNetResult EditAnswer(int id, int answerId, string title, int factorTypeId, int scoreId, string keyInfo, string rationale)
        {
            FactorEntity temp = null;
            if (answerId > 0)
            {
                temp = Service.FactorUpdate(id, answerId, factorTypeId, scoreId, title, keyInfo, rationale);
            }
            else
            {
                temp = Service.FactorAdd(id, factorTypeId, scoreId, title, keyInfo, rationale);
                answerId = temp.Id;
            }
            string label = temp.Label;
            return new JsonNetResult(new { FactorId = answerId, Success = true, Label = label, Title = title });
        }

        [HttpPost]
        public JsonNetResult Select(int id, int answerId, int recommendationId, bool applyAll = false)
        {
			Service.FactorAssociate(id, recommendationId, answerId, applyAll); //BB hard coded false here, you'll want to bind to a checkbox ***********************
            FactorEntity entity = Service.FactorGet(answerId);
            return new JsonNetResult(entity);
        }

        [HttpPost]
        public JsonNetResult SelectForMultipleRecs(int id, int answerId, int locationId, int bodyOfWaterId, int methodId, int factorTypeId)
        {
            Service.FactorAssociate(id, locationId, bodyOfWaterId, methodId, answerId, factorTypeId); 
            FactorEntity entity = Service.FactorGet(answerId);
            return new JsonNetResult(entity);
        }

        [HttpGet]
        public JsonNetResult Scores(int factorTypeId)
        {
            IList<RowsourceEntity> scores = Service.FactorScore(factorTypeId);
            return new JsonNetResult(scores);
        }
        #endregion

    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Controllers/ExpertInputController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ART;

namespace MontereyBayAquarium.Swat.Web.Controllers
{
    [Authorize]
    public class ExpertInputController : ControllerBase
    {
        [HttpGet]
        public ViewResult Index(int id)
        {
            IList<FeedbackEntity> model = PublicService.FeedbackGet(id);
            return View("Index", model);
        }

        [HttpGet]
        public ViewResult Details(int id, int expertInputId)
        {
            FeedbackEntity model = PublicService.LoadFeedback(expertInputId);
            model.Documents = PublicService.GetFeedbackAttachments(expertInputId);
            return View("View", model);
        }

    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ART;
using MontereyBayAquarium.Swat.Web.ActionResults;



namespace MontereyBayAquarium.Swat.Web.Controllers
{
    public class ImageController : ControllerBase
    {

        #region Index

        public ViewResult Index(int id, string keywords)
        {
            string Keywords = "";
            if (keywords != null) { Keywords = keywords; }
            IList<ImageEntity> model = new List<ImageEntity>();
            model = Service.ImageList(id, Keywords);
            return View("Index", model);
        }
        #endregion

        #region Edit
        [HttpGet]
        public ViewResult Edit(int id, int imageId)
        {
            ImageEntity model = Service.ImageGet(id, imageId);
            return View("Edit", model);
        }
        
        
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, ImageEntity image, HttpPostedFileBase file)
        {
            string[] mediaExtensions = {
                ".PNG", ".JPG", ".JPEG", ".BMP", ".GIF"
            };

            if (image.ImageId > 0)
            {
                if (file == null)
                {
                    Service.ImageUpdate(image.ReportId, image.ImageId, image.Name, image.Description, image.Path);
                }
                else
                {
                    string path = Helpers.SaveFile(file, Server, "images/"+image.ReportId.ToString() + "/");
                    if (mediaExtensions.Contains(Path.GetExtension(path).ToUpperInvariant()))
                    {
                        Service.ImageUpdate(image.ReportId, image.ImageId, image.Name, image.Description, path);
                    }
                    else
                    {
                        TempData["error"] = "Please upload an image file of type PNG, JPG, or GIF";
                        return RedirectToAction("Edit", new { id = id, imageId = image.ImageId});
                    }
                }
                
            }
            else
            {
                string path = Helpers.SaveFile(file, Server, "images/" + image.ReportId.ToString() + "/");
                if (mediaExtensions.Contains(Path.GetExtension(path).ToUpperInvariant()))
                {
                    Service.ImageAdd(id, image.Name, image.Description, path);
                }
                else
                {
                    TempData["error"] = "Please upload an image file of type PNG, JPG, or GIF";
                    return RedirectToAction("Edit", new { id = id, imageId = image.ImageId });
                }
            }
			return RedirectToAction("Index");
        }
        #endregion

        [HttpPost]
        public JsonNetResult Delete(int id, int imageId)
        {
            Service.ImageDelete(id, imageId);
            return new JsonNetResult(new {success = true});
        }
        [HttpPost]
        public ActionResult Search(int id, string filter, string context)
        {
            ViewBag.Context = context;
            IList<ImageEntity> model = new List<ImageEntity>();
            model = Service.ImageList(id, filter ?? String.Empty);
            return View("_Images", model);
        }

        [HttpGet]
        public ViewResult Search(int id)
        {
            ViewBag.Context = "Modal";
            IList<ImageEntity> model = new List<ImageEntity>();
            model = Service.ImageList(id, String.Empty);
            return View("_Images", model);
        }

    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Controllers/ReferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ART;
using MontereyBayAquarium.Swat.Web.Models.References;
using MontereyBayAquarium.Swat.Web.ActionResults;
using System.Text.RegularExpressions;



namespace MontereyBayAquarium.Swat.Web.Controllers
{
    public class ReferenceController : ControllerBase
    {

        #region Index

        public ViewResult Index(int id, string keywords)
        {
            string Keywords = "";
            if (keywords != null) { Keywords = keywords; }
            ReferencesViewModel model = new ReferencesViewModel();
            model.References = Service.ReferenceList(id, Keywords);
            return View("Index", model);
        }
        #endregion

        #region Edit
        [HttpGet]
        public ViewResult Edit(int id, int referenceId)
        {
            ReferenceEntity model = Service.ReferenceGet(id, referenceId);
            return View("Edit", model);
        }
        
        
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, int referenceId, ReferenceEntity reference, HttpPostedFileBase documentation, string documentationType, string link)
        {
            //reference.Title = ""; //title is no longer needed TODO: Update Service Layer to take out title field
            bool isUrl = false;
            string path = "";
            RegexOptions options = RegexOptions.None;
            Regex regex = new Regex(@"[ ]{2,}", options);
            reference.ShortName = regex.Replace(reference.ShortName, @" ");
            if (reference.ReferenceId > 0)
            {
                ReferenceEntity oldReference = Service.ReferenceGet(reference.ReportId, reference.ReferenceId); // get the actual reference because there's no "path" or "isUrl" in the form
                isUrl = oldReference.isUrl;
                path = (oldReference.Path != null) ? oldReference.Path : "";
            }
            if (documentationType == "link") //documentationType = 0 unless the user purposefully want to upload something 
            {
                isUrl = true;
                path =  new UriBuilder(link).Uri.AbsoluteUri;
            }
           
			if (documentationType == "document") path = Helpers.SaveFile(documentation, Server, "references/"+id.ToString()+"/");

            bool shortNameIsValid = true;
            int updatedReferenceId = 0;

			if (reference.ReferenceId > 0)
                shortNameIsValid = Service.ReferenceUpdate(id, reference.ReferenceId, reference.ShortName, reference.Bibliography, reference.Authors, reference.Year, path, isUrl); //TODO GenEx
			else 
			    updatedReferenceId = Service.ReferenceAdd(id, reference.ShortName, reference.Bibliography, reference.Authors, reference.Year, path, isUrl); //TODO GenEx

            if (!shortNameIsValid || updatedReferenceId == -1)
            {
                TempData["error"] = "An existing reference already exists with the same shortname.";
                return RedirectToAction("Edit", new { id = id, referenceId = referenceId });
            }
			
			return RedirectToAction("Index");
        }
        #endregion

        [HttpPost]
        public JsonNetResult Delete(int id, int referenceId)
        {
            Service.ReferenceDelete(id, referenceId);
            return new JsonNetResult(new {success = true});
        }
        [HttpPost]
        public ActionResult Search(int id, string filter, string context)
        {
            ViewBag.Context = context;
            string Keywords = "";
            if (filter != null) { Keywords = filter; }
            ReferencesViewModel model = new ReferencesViewModel();
            model.References = Service.ReferenceList(id, Keywords);
            //return View("Index", model);
            return View("_References", model);
        }

        [HttpGet]
        public ViewResult Search(int id)
        {
            ViewBag.Context = "Modal";
            string Keywords = "";
            ReferencesViewModel model = new ReferencesViewModel();
            model.References = Service.ReferenceList(id, Keywords);
            return View("_References", model);
        }

    }
}

src/ART/MontereyBayAquiarum.Swat.Web/Views/Shared/_AnalysisLayout.cshtml
@{
    Layout = "~/Views/Shared/_LoggedInLayout.cshtml";
}

    <div class="analysis-layout">
        
        <div class="analysis-wrapper">
            
            @Html.Action("AnalysisHeader", "Analysis", new { id = @ViewContext.RouteData.Values["id"] })
            
            <div class="tabbed-wrapper">
                <ul class="tabs">
                    <li><a href="@Url.Action("DefineScope", "Analysis")"><span>Main Species</span></a></li>
                    <li><a href="@Url.Action("Criteria1", "Analysis")"><span>Assessment</span></a></li>
                    <li><a href="@Url.Action("ExecutiveSummary", "Analysis")"><span>Supporting Info</span></a></li>
                    <li class="report-preview"><a href="@Url.Action("Preview", "Analysis")"><span>Report Preview</span></a></li>
                </ul>
                <a class="resources">Resources<span></span></a>
                <ul class="resources-drop">
                    <li><a class="red-link" href="@Url.Action("Index", "Answer")">Answers</a></li>
                    <li><a class="red-link" href="@Url.Action("Index", "Reference")">Reference</a></li>
                    <li><a class="red-link" href="@Url.Action("Index", "ExpertInput")">Expert Input</a></li>
                    <li class="bottom"><a class="red-link" href="@Url.Action("Index", "Image")">Images</a></li>
                </ul>
                <div class="clear"></div>
                <div class="tabbed-content">
                    <div class="top">
                    </div>
                    <div class="middle">
                        @RenderBody()
                    </div>
                    <div class="bottom">
                    </div>
                </div>
            </div>

        </div>

    </div>

  

src/ART/MontereyBayAquiarum.Swat.Web/Views/Shared/_AnswerList.cshtml
@model AnswerListViewModel
@using ART;
@using MontereyBayAquarium.Swat.Web.Models.Shared;

<!--<h2>Select another answer</h2>-->
<a class="button-review" id="go-back" href="#">    <span class="l">Go Back</span>
    <span class="r"></span></a>
<a href="/reports/@ViewContext.RouteData.Values["id"]/answers/0/edit" class="add-answer button-review add-row">
    <span class="l">Add New</span>
    <span class="r"></span>
    <span class="plus"></span>
</a>
<div class="search" reportId="@ViewContext.RouteData.Values["id"]" factorTypeId="@Model.CurrentFactorTypeId">
    <label>Search: </label>
    <input type="text" id="search-answer" />
    <a class="button-review bulk-add search-answer">
        <span class="l">GO</span>
        <span class="r"></span>
    </a>
    <div class="clear"></div>
</div>
   <div id="pager" data-pagesize="@HttpContext.Current.Session["pageSize"]">
   <form>
        
        <a class="first"></a>
		<a class="prev"></a>

		<span class="pagedisplay"></span>

		<a class="next"></a>
        <a class="last"></a>

        <span class="answer-amount">@Model.Answers.Count Answers</span>
        @{
            int pageSize;
            if (HttpContext.Current.Session["pageSize"] != null)
            {
                pageSize = (int)HttpContext.Current.Session["pageSize"];
            }
            else
            {
                pageSize = 10;   
            }
         }
		<select class="pagesize">
			<option @(pageSize == 10 ? "selected='selected'" : "") value="10">10</option>
			<option @(pageSize == 20 ? "selected='selected'" : "") value="20">20</option>
			<option @(pageSize == 30 ? "selected='selected'" : "") value="30">30</option>
			<option @(pageSize == 40 ? "selected='selected'" : "")  value="40">40</option>
		</select>
        <span class="pagesize-text">Answers per page</span>
        <div class="clear"></div>
	</form>
   </div>
    <table id="answer-list" cellspacing="1" class="tablesorter">             
        <thead>
            <tr> 
                <th class="left-cap reference-id">ID</th> 
                <th class="factor">Factor</th>
                <th>Score</th> 
                <th class="justification">Justification</th> 
                <th class="right-cap">&nbsp;</th> 
            </tr> 
        </thead> 
        <tbody> 
        @foreach (FactorEntity factor in Model.Answers)
        {
            <tr> 
                <td class="left-cap"><a class="factor-id" factorId="@factor.Id">@factor.Label</a></td> 

                <td>@{
               var temp = Model.FactorTypes.Where(FactorType => factor.FactorTypeId == FactorType.Key).SingleOrDefault();
               if (temp != null)
               {
                        @(temp.Value)
               }
                    }</td>
                <td class="grey-score"><span class="score-grey">@factor.FactorScore</span>@factor.FactorScoreDescription</td>
                <td class="answer-info">
                   <div class="key-relevant-info">
                    <h4>Key Relevant Info:</h4>
                    <p>@Html.Raw(factor.KeyInfo)</p>
                   </div>
                   <div class="detail-rationale">
                       <h4>Detailed Rationale:</h4>
                       <p>@Html.Raw(factor.Rationale)</p>
                   </div>
                   <a>Show More</a>
                </td>
                <td class="right-cap five">
                    <a class="edit-row"  href="@Url.Action("Edit", "Answer", new { id = ViewContext.RouteData.Values["id"], answerId = factor.Id })"></a>
                    <a class="delete-row" href="@Url.Action("Delete", "Answer", new { id = ViewContext.RouteData.Values["id"], answerId = factor.Id })"></a>
                </td> 
            </tr> 
        }
            <!--<tr> 
                <td class="left-cap"><a>1.1-B</a></td> 
                <td>1.1</td> 
                <td><span class="score-grey">4</span>Unknown or risk of overfishing</td>
                <td class="answers-info">
                  <div class="key-relevant-info">
                    <h4>Key Relevant Info:</h4>
                    <p>I do not think anyone would be interested in catching this fish since it tastes truly disgusting and smells like Ron Jeremy.</p>
                  </div>
                  <div class="detail-rationale">
                     <h4>Detailed Rationale:</h4>
                     <p>This fish is so gross tasting that I would rather eat deep fried elephant poop than to eat this fish.</p>
                  </div>
                  <a>Show More</a>
                </td>
                <td class="right-cap">
                    <a class="edit-row"  href="/reports/1/answers/1/edit"></a>
                    <a class="delete-row"></a>
                </td> 
            </tr> -->
        </tbody> 
    </table>

src/ART/MontereyBayAquiarum.Swat.Web/Views/Shared/_AnswerModal.cshtml
<div id="answer-modal" reportId="@ViewContext.RouteData.Values["id"]">
    <div class="clear"></div>
    <h2 id="modal-title"></h2>
    <ul class="tabs">
        <li class="on"><a><p>Details</p></a></li>
        <li><a><p>Comments <label id="count"></label></p></a></li>
        <div class="clear"></div>
    </ul>
    <div class="tab-rule"></div>
    <div class="details content on">
    </div>
    <div class="references">
        <h2>Attach References</h2>
        <div id="reference-container">
            @Html.Action("Search", "Reference", new { id = ViewContext.RouteData.Values["id"] }) 
        </div>
    </div>
    <div class="images">
        <h2>Attach Images</h2>
        <div id="image-container">
            @Html.Action("Search", "Image", new { id = ViewContext.RouteData.Values["id"]})
        </div>
    </div>
    <div class="comments content">
        
    </div>
</div>

<script type="text/html" id="risk-factor">
<div class="cell-wrapper">
    <ul class="risk-factor" factorId="<%= criteria.factorId %>" factorTypeId="<%= criteria.factorTypeId %>">
        <li>
            <span class="risk-number"><%= criteria.score %></span>
            <span class="risk-text"><%= criteria.scoreDescription %></span>
        </li>
        <li>
        <span class="risk-answer-ref"><%= criteria.label %></span>
        <%
        if (criteria.commentCount > 0) { %>
            <span class="risk-comment"><%= criteria.commentCount %>
            </span>
        <% } %>
        </li>
    </ul>
    <ul class="risk-factor-popup">
        <li class="popup-head">
            <%= criteria.label %>: <%= criteria.title %>
        </li>
        <li class="priority">
            <p>
                <span class="number"><%= criteria.score %></span> <span class="text"><%= criteria.scoreDescription %></span>
            </p>
        </li>
        <li class="key-info"><span>Key Relevant Info:</span>
            <p><%= criteria.keyInfo %></p>
        </li>
    </ul>
</div>
</script>

src/ART/MontereyBayAquiarum.Swat.Web/Views/Shared/_DeleteConfirmationModal.cshtml
<div id="delete-modal">
<p>Are you sure you want to delete?</p>
<a class="yes">Yes</a><a class="no">No</a>
</div>

src/ART/MontereyBayAquiarum.Swat.Web/Views/Shared/_EditAnswer.cshtml
@model MontereyBayAquarium.Swat.Web.Models.Answer.EditAnswerViewModel
@using ART;

@if (Model.Factor.FactorTypeId != 0)
{
<h2 class="answer-header">Answer: @Model.Factor.Label</h2>
}
else
{
    <h2 class="answer-header">Create a new answer</h2>
}

<!--div class="tab-rule"></div-->
<a class="select-different-answer">
    <span></span>
    Select a different answer
</a>

<form method="post" action="" class="details @{if(Model.Factor.FactorTypeId == 0) { @:new  
 }}" id="reference-form" style="display: block">
    <div id="factor-instruction-container">
        @Html.Action("FactorInstruction", "Analysis", new { title = "Help", factorTypeId = Model.Factor.FactorTypeId })
    </div>
    <ul>
        <li class="hide">
            <label class="field-name-text">Answer Name:</label>
            <input value="@Model.Factor.Title" title=""  class="required" id="title" name="title" />
        </li>
        <li class="hide">
            <label class="field-name-text">Factor:</label>
            <select id="factor" name="factorTypeId" class="required" @(Model.FactorTypes.Count == 1 ? "disabled='disabled'" : "")>
              <option value="Select One">Select One</option>
              @foreach (RowsourceEntity factorType in Model.FactorTypes)
              {
                if (factorType != null)
                {
                    <option value="@factorType.Key" @(Model.FactorTypes.Count == 1 || factorType.Key == Model.Factor.FactorTypeId ? "selected='selected'" : "")>@factorType.Value</option>
                }
              }
            </select>
            @{
                if(Model.FactorTypes.Count == 1){
                    <input type="hidden" name="factorTypeId" value="@Model.Factor.FactorTypeId" />   
                }
            }
        </li>
        <li>
            <label class="field-name-text">Score:</label>
            <select id="score" name="scoreid" class="required">
            @if (Model.Scores == null)
            {
              <option value="0" selected="">Select One</option>
            }
              @if (Model.Scores != null)
              {
                  foreach (RowsourceEntity score in Model.Scores)
                  {
                  <option value="@score.Key" @(score.Value ==  Model.Factor.FactorScoreDescription ? "selected='selected'" : "")>@score.Value</option>
                  }
              }
              <!--<option value="1 - Low">1 - Low</option>
              <option value="2 - Medium">2 - Medium</option>
              <option value="3 - High">3 - High</option>-->
            </select>
        </li>
        <li>
            <label class="field-name-text full-line">Key Relevant Info: <span>(We recommend a maximum of 800 characters)</span></label>
            <div class="clear"></div>
            <a class="button-review document-insert"><span class="l">Insert Reference</span><span class="r"></span><span class="document-insert-icon"></span></a>
            <div class="clear"></div>
            <textarea class="mceEditor" id="keyInfo" name="keyInfo">@Model.Factor.KeyInfo</textarea>
        </li>
        <li>
            <label class="field-name-text full-line">Detailed Rationale: <span> (Optional)</span></label>
            <div class="clear"></div>
            <a class="button-review document-insert"><span class="l">Insert Reference</span><span class="r"></span><span class="document-insert-icon"></span></a>
            <a class="button-review image-insert"><span class="l">Insert Image</span><span class="r"></span></a>
            <div class="clear"></div>
            <textarea class="mceFullEditor" id="rationale" name="rationale">@Model.Factor.Rationale</textarea>
        </li>
        <li><a class="save-area submit button-on"><span class="l">Save</span><span class="r"></span></a><span class="cancel-area cancel-modal"> or <a href="@Url.Action("Index", "Answer", new { id = ViewContext.RouteData.Values["id"] })">Cancel</a></span></li>
        <li>&nbsp;</li>
        </ul>
</form>

<div class="clear"></div>
<div id="validation-modal">
    <p class="active">Please select a score.</p>
</div> 